name: gadgetron
channels:
  - pytorch
  - rapidsai
  - nvidia/label/cuda-12.8.0
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - anaconda-client=1.11                # dev
  - armadillo=9.900.5                   # dev
  - boost=1.80.0
  - breathe=4.34                        # dev
  - cmake=3.21.3                        # dev
  - conda-build=3.23                    # dev
  - conda-verify=3.1                    # dev
  - cuda-cudart                         # cuda
  - cuda-cudart-dev                     # cuda, dev
  - cuda-cccl                           # cuda
  - cuda-driver-dev                     # cuda, dev
  - cuda-libraries-dev                  # cuda, dev
  - cuda-libraries                      # cuda
  - cuda-runtime                        # cuda
  - cuda-nvcc                           # cuda, dev
  - cuda-nvrtc                          # cuda
  - cuda-nvrtc-dev                      # cuda, dev
#  - pynvjitlink
  - cudnn
  - cupy
  

  - pip:
      - sigpy
      - junitparser==2.2.0
      - scikit-image
      - nibabel
      - numpy==1.23
      - antspyx
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch==2.4.0
      - torchvision==0.19.0
      - torchaudio==2.4.0
      - onnx
      - einops
      - wandb
      - onnxruntime-gpu


